// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as OrganizationTable } from './Organization';
import type { default as UserTable } from './User';
import type { default as MemberTable } from './Member';
import type { default as OrganizationMemberTable } from './OrganizationMember';

export default interface IdentitySchema {
  'identity.organization': OrganizationTable;

  'identity.user': UserTable;

  'identity.member': MemberTable;

  'identity.organizationMember': OrganizationMemberTable;
}
