// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table identity.member */
export default interface MemberTable {
  id: ColumnType<string, string | undefined, string>;

  email: ColumnType<string, string, string>;

  walletAddress: ColumnType<string | null, string | null, string | null>;

  firstName: ColumnType<string | null, string | null, string | null>;

  lastName: ColumnType<string | null, string | null, string | null>;

  phone: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type MemberDb = Selectable<MemberTable>;

export type MemberCreateDb = Insertable<MemberTable>;

export type MemberUpdateDb = Updateable<MemberTable>;
