// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table identity.organization */
export default interface OrganizationTable {
  id: ColumnType<string, string | undefined, string>;

  name: ColumnType<string, string, string>;

  legalName: ColumnType<string | null, string | null, string | null>;

  taxId: ColumnType<string | null, string | null, string | null>;

  walletAddress: ColumnType<string | null, string | null, string | null>;

  timezone: ColumnType<string, string | undefined, string>;

  email: ColumnType<string | null, string | null, string | null>;

  phone: ColumnType<string | null, string | null, string | null>;

  addressLine1: ColumnType<string | null, string | null, string | null>;

  addressLine2: ColumnType<string | null, string | null, string | null>;

  city: ColumnType<string | null, string | null, string | null>;

  state: ColumnType<string | null, string | null, string | null>;

  postalCode: ColumnType<string | null, string | null, string | null>;

  country: ColumnType<string | null, string | null, string | null>;

  kybStatus: ColumnType<string | null, string | null, string | null>;

  kybCompletedAt: ColumnType<string | null, string | null, string | null>;

  isWhitelisted: ColumnType<boolean | null, boolean | null, boolean | null>;

  whitelistedAt: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type OrganizationDb = Selectable<OrganizationTable>;

export type OrganizationCreateDb = Insertable<OrganizationTable>;

export type OrganizationUpdateDb = Updateable<OrganizationTable>;
