// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table identity.organization_member */
export default interface OrganizationMemberTable {
  organizationId: ColumnType<string, string, string>;

  memberId: ColumnType<string, string, string>;

  role: ColumnType<string, string, string>;

  joinedAt: ColumnType<Date, Date | string | undefined, Date | string>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type OrganizationMemberDb = Selectable<OrganizationMemberTable>;

export type OrganizationMemberCreateDb = Insertable<OrganizationMemberTable>;

export type OrganizationMemberUpdateDb = Updateable<OrganizationMemberTable>;
