// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table identity.user */
export default interface UserTable {
  id: ColumnType<string, string | undefined, string>;

  email: ColumnType<string, string, string>;

  walletAddress: ColumnType<string | null, string | null, string | null>;

  firstName: ColumnType<string | null, string | null, string | null>;

  lastName: ColumnType<string | null, string | null, string | null>;

  phone: ColumnType<string | null, string | null, string | null>;

  country: ColumnType<string | null, string | null, string | null>;

  kycStatus: ColumnType<string | null, string | null, string | null>;

  kycCompletedAt: ColumnType<string | null, string | null, string | null>;

  isWhitelisted: ColumnType<boolean | null, boolean | null, boolean | null>;

  whitelistedAt: ColumnType<string | null, string | null, string | null>;

  isAccreditedInvestor: ColumnType<boolean | null, boolean | null, boolean | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type UserDb = Selectable<UserTable>;

export type UserCreateDb = Insertable<UserTable>;

export type UserUpdateDb = Updateable<UserTable>;
