// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as InvestmentSchema } from './investment/InvestmentSchema';
import type { default as InvoiceSchema } from './invoice/InvoiceSchema';
import type { default as BusinessSchema } from './business/BusinessSchema';
import type { default as IdentitySchema } from './identity/IdentitySchema';
import type { default as BlockchainSchema } from './blockchain/BlockchainSchema';

type Database = InvestmentSchema & InvoiceSchema & BusinessSchema & IdentitySchema & BlockchainSchema;

export default Database;
