// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as InvestorPositionTable } from './InvestorPosition';
import type { default as YieldCalculationTable } from './YieldCalculation';
import type { default as RepaymentDistributionTable } from './RepaymentDistribution';

export default interface InvestmentSchema {
  'investment.investorPosition': InvestorPositionTable;

  'investment.yieldCalculation': YieldCalculationTable;

  'investment.repaymentDistribution': RepaymentDistributionTable;
}
