// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table investment.investor_position */
export default interface InvestorPositionTable {
  id: ColumnType<string, string | undefined, string>;

  userId: ColumnType<string, string, string>;

  invoiceId: ColumnType<string, string, string>;

  nftId: ColumnType<string, string, string>;

  fundedAt: ColumnType<string, string, string>;

  maturityDate: ColumnType<string, string, string>;

  positionStatus: ColumnType<string, string | undefined, string>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  principalAmount: ColumnType<string, string, string>;

  expectedReturn: ColumnType<string, string, string>;

  actualReturn: ColumnType<string | null, string | null, string | null>;

  apr: ColumnType<string, string, string>;
}

export type InvestorPositionDb = Selectable<InvestorPositionTable>;

export type InvestorPositionCreateDb = Insertable<InvestorPositionTable>;

export type InvestorPositionUpdateDb = Updateable<InvestorPositionTable>;
