// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table investment.repayment_distribution */
export default interface RepaymentDistributionTable {
  id: ColumnType<string, string | undefined, string>;

  positionId: ColumnType<string, string, string>;

  invoiceId: ColumnType<string, string, string>;

  investorAddress: ColumnType<string, string, string>;

  distributedAt: ColumnType<string, string, string>;

  distributionTxHash: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  principalReturned: ColumnType<string, string, string>;

  yieldReceived: ColumnType<string, string, string>;

  totalAmount: ColumnType<string, string, string>;
}

export type RepaymentDistributionDb = Selectable<RepaymentDistributionTable>;

export type RepaymentDistributionCreateDb = Insertable<RepaymentDistributionTable>;

export type RepaymentDistributionUpdateDb = Updateable<RepaymentDistributionTable>;
