// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table investment.yield_calculation */
export default interface YieldCalculationTable {
  id: ColumnType<string, string | undefined, string>;

  positionId: ColumnType<string, string, string>;

  principalCents: ColumnType<string, string, string>;

  aprBps: ColumnType<string, string, string>;

  fundingTimestamp: ColumnType<string, string, string>;

  dueTimestamp: ColumnType<string, string, string>;

  durationDays: ColumnType<number, number, number>;

  totalYieldCents: ColumnType<string, string, string>;

  investorYieldCents: ColumnType<string, string, string>;

  platformFeeCents: ColumnType<string, string, string>;

  platformFeeRateBps: ColumnType<string, string | undefined, string>;

  calculatedAt: ColumnType<string, string, string>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type YieldCalculationDb = Selectable<YieldCalculationTable>;

export type YieldCalculationCreateDb = Insertable<YieldCalculationTable>;

export type YieldCalculationUpdateDb = Updateable<YieldCalculationTable>;
