// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table investment.yield_calculation */
export default interface YieldCalculationTable {
  id: ColumnType<string, string | undefined, string>;

  positionId: ColumnType<string, string, string>;

  fundingTimestamp: ColumnType<string, string, string>;

  dueTimestamp: ColumnType<string, string, string>;

  durationDays: ColumnType<number, number, number>;

  calculatedAt: ColumnType<string, string, string>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  principal: ColumnType<string, string, string>;

  apr: ColumnType<string, string, string>;

  totalYield: ColumnType<string, string, string>;

  investorYield: ColumnType<string, string, string>;

  platformFee: ColumnType<string, string, string>;

  platformFeeRate: ColumnType<string, string, string>;

  /** Unix timestamp when the yield was settled/distributed to the investor (UTC) */
  settledAt: ColumnType<string | null, string | null, string | null>;
}

export type YieldCalculationDb = Selectable<YieldCalculationTable>;

export type YieldCalculationCreateDb = Insertable<YieldCalculationTable>;

export type YieldCalculationUpdateDb = Updateable<YieldCalculationTable>;
