// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as ContractEventTable } from './ContractEvent';
import type { default as TransactionTable } from './Transaction';
import type { default as WalletAutopayConfigTable } from './WalletAutopayConfig';
import type { default as InvoiceNftTable } from './InvoiceNft';

export default interface BlockchainSchema {
  'blockchain.contractEvent': ContractEventTable;

  'blockchain.transaction': TransactionTable;

  'blockchain.walletAutopayConfig': WalletAutopayConfigTable;

  'blockchain.invoiceNft': InvoiceNftTable;
}
