// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table blockchain.contract_event */
export default interface ContractEventTable {
  id: ColumnType<string, string | undefined, string>;

  eventName: ColumnType<string, string, string>;

  contractAddress: ColumnType<string, string, string>;

  txHash: ColumnType<string, string, string>;

  blockNumber: ColumnType<string, string, string>;

  blockTimestamp: ColumnType<string, string, string>;

  logIndex: ColumnType<number, number, number>;

  invoiceTokenId: ColumnType<string | null, string | null, string | null>;

  eventData: ColumnType<unknown, unknown, unknown>;

  processed: ColumnType<boolean | null, boolean | null, boolean | null>;

  processedAt: ColumnType<string | null, string | null, string | null>;

  processingError: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type ContractEventDb = Selectable<ContractEventTable>;

export type ContractEventCreateDb = Insertable<ContractEventTable>;

export type ContractEventUpdateDb = Updateable<ContractEventTable>;
