// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table blockchain.invoice_nft */
export default interface InvoiceNftTable {
  id: ColumnType<string, string | undefined, string>;

  invoiceId: ColumnType<string, string, string>;

  tokenId: ColumnType<string, string, string>;

  contractAddress: ColumnType<string, string, string>;

  chainId: ColumnType<number, number | undefined, number>;

  ownerAddress: ColumnType<string | null, string | null, string | null>;

  metadataUri: ColumnType<string | null, string | null, string | null>;

  mintedAt: ColumnType<string, string, string>;

  mintedTxHash: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type InvoiceNftDb = Selectable<InvoiceNftTable>;

export type InvoiceNftCreateDb = Insertable<InvoiceNftTable>;

export type InvoiceNftUpdateDb = Updateable<InvoiceNftTable>;
