// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table blockchain.transaction */
export default interface TransactionTable {
  id: ColumnType<string, string | undefined, string>;

  nftId: ColumnType<string | null, string | null, string | null>;

  txHash: ColumnType<string, string, string>;

  txType: ColumnType<string, string, string>;

  fromAddress: ColumnType<string | null, string | null, string | null>;

  toAddress: ColumnType<string | null, string | null, string | null>;

  blockNumber: ColumnType<string, string, string>;

  blockTimestamp: ColumnType<string, string, string>;

  gasUsed: ColumnType<string | null, string | null, string | null>;

  gasPriceWei: ColumnType<string | null, string | null, string | null>;

  status: ColumnType<string, string | undefined, string>;

  errorMessage: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  amount: ColumnType<string | null, string | null, string | null>;
}

export type TransactionDb = Selectable<TransactionTable>;

export type TransactionCreateDb = Insertable<TransactionTable>;

export type TransactionUpdateDb = Updateable<TransactionTable>;
