// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table blockchain.wallet_autopay_config */
export default interface WalletAutopayConfigTable {
  id: ColumnType<string, string | undefined, string>;

  invoiceId: ColumnType<string, string, string>;

  organizationId: ColumnType<string, string, string>;

  method: ColumnType<string, string, string>;

  enabled: ColumnType<boolean, boolean | undefined, boolean>;

  walletAddress: ColumnType<string | null, string | null, string | null>;

  approvedAt: ColumnType<string | null, string | null, string | null>;

  achBankAccountId: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  approvedAmount: ColumnType<string | null, string | null, string | null>;
}

export type WalletAutopayConfigDb = Selectable<WalletAutopayConfigTable>;

export type WalletAutopayConfigCreateDb = Insertable<WalletAutopayConfigTable>;

export type WalletAutopayConfigUpdateDb = Updateable<WalletAutopayConfigTable>;
