// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/**
 * Represents the table invoice.invoice
 * Core invoice entity with two-tier status model (lifecycle_status for full journey, on_chain_status for smart contract states)
 */
export default interface InvoiceTable {
  id: ColumnType<string, string | undefined, string>;

  organizationId: ColumnType<string, string, string>;

  payerCompanyId: ColumnType<string, string, string>;

  /** Invoice principal amount in cents (e.g., $10,000 = 1000000) */
  amountCents: ColumnType<string, string, string>;

  /** Annual Percentage Rate in basis points (e.g., 36.5% = 3650) */
  aprBps: ColumnType<string | null, string | null, string | null>;

  discountRateBps: ColumnType<string | null, string | null, string | null>;

  invoiceDate: ColumnType<string, string, string>;

  /** Unix timestamp when payment is due (UTC) */
  dueAt: ColumnType<string, string, string>;

  /** Complete lifecycle status (17 states: Draft → Settled/Defaulted) */
  lifecycleStatus: ColumnType<string, string | undefined, string>;

  /** Smart contract status only (5 states: LISTED, FUNDED, FULLY_PAID, SETTLED, DEFAULTED) */
  onChainStatus: ColumnType<string | null, string | null, string | null>;

  invoiceNumber: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  metadataUri: ColumnType<string | null, string | null, string | null>;

  riskScore: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type InvoiceDb = Selectable<InvoiceTable>;

export type InvoiceCreateDb = Insertable<InvoiceTable>;

export type InvoiceUpdateDb = Updateable<InvoiceTable>;
