// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table invoice.invoice_repayment */
export default interface InvoiceRepaymentTable {
  id: ColumnType<string, string | undefined, string>;

  invoiceId: ColumnType<string, string, string>;

  depositedBy: ColumnType<string | null, string | null, string | null>;

  depositedAt: ColumnType<string, string, string>;

  settledAt: ColumnType<string | null, string | null, string | null>;

  repaymentTxHash: ColumnType<string | null, string | null, string | null>;

  settlementTxHash: ColumnType<string | null, string | null, string | null>;

  repaymentMethod: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  repaymentAmount: ColumnType<string, string, string>;
}

export type InvoiceRepaymentDb = Selectable<InvoiceRepaymentTable>;

export type InvoiceRepaymentCreateDb = Insertable<InvoiceRepaymentTable>;

export type InvoiceRepaymentUpdateDb = Updateable<InvoiceRepaymentTable>;
