// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table invoice.invoice_status_history */
export default interface InvoiceStatusHistoryTable {
  id: ColumnType<string, string | undefined, string>;

  invoiceId: ColumnType<string, string, string>;

  fromStatus: ColumnType<string, string, string>;

  toStatus: ColumnType<string, string, string>;

  changedBy: ColumnType<string | null, string | null, string | null>;

  changedAt: ColumnType<string, string, string>;

  reason: ColumnType<string | null, string | null, string | null>;

  metadata: ColumnType<unknown | null, unknown | null, unknown | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type InvoiceStatusHistoryDb = Selectable<InvoiceStatusHistoryTable>;

export type InvoiceStatusHistoryCreateDb = Insertable<InvoiceStatusHistoryTable>;

export type InvoiceStatusHistoryUpdateDb = Updateable<InvoiceStatusHistoryTable>;
