// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as InvoiceUnderwritingTable } from './InvoiceUnderwriting';
import type { default as InvoiceTable } from './Invoice';
import type { default as InvoiceDefaultTable } from './InvoiceDefault';
import type { default as InvoiceStatusHistoryTable } from './InvoiceStatusHistory';
import type { default as InvoiceFundingDetailTable } from './InvoiceFundingDetail';
import type { default as InvoiceRepaymentTable } from './InvoiceRepayment';
import type { default as InvoiceDocumentTable } from './InvoiceDocument';

export default interface InvoiceSchema {
  'invoice.invoiceUnderwriting': InvoiceUnderwritingTable;

  'invoice.invoice': InvoiceTable;

  'invoice.invoiceDefault': InvoiceDefaultTable;

  'invoice.invoiceStatusHistory': InvoiceStatusHistoryTable;

  'invoice.invoiceFundingDetail': InvoiceFundingDetailTable;

  'invoice.invoiceRepayment': InvoiceRepaymentTable;

  'invoice.invoiceDocument': InvoiceDocumentTable;
}
