// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table invoice.invoice_underwriting */
export default interface InvoiceUnderwritingTable {
  id: ColumnType<string, string | undefined, string>;

  invoiceId: ColumnType<string, string, string>;

  underwriterId: ColumnType<string | null, string | null, string | null>;

  decision: ColumnType<string, string, string>;

  decisionReason: ColumnType<string | null, string | null, string | null>;

  assessedRiskScore: ColumnType<string | null, string | null, string | null>;

  fraudCheckStatus: ColumnType<string | null, string | null, string | null>;

  payerVerificationStatus: ColumnType<string | null, string | null, string | null>;

  completedAt: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  approvedAmount: ColumnType<string | null, string | null, string | null>;

  approvedApr: ColumnType<string | null, string | null, string | null>;
}

export type InvoiceUnderwritingDb = Selectable<InvoiceUnderwritingTable>;

export type InvoiceUnderwritingCreateDb = Insertable<InvoiceUnderwritingTable>;

export type InvoiceUnderwritingUpdateDb = Updateable<InvoiceUnderwritingTable>;
