// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table invoice.invoice_funding_detail */
export default interface InvoiceFundingDetailTable {
  id: ColumnType<string, string | undefined, string>;

  invoiceId: ColumnType<string, string, string>;

  investorAddress: ColumnType<string, string, string>;

  fundedAt: ColumnType<string, string, string>;

  fundingTxHash: ColumnType<string | null, string | null, string | null>;

  paymentTokenAddress: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  fundedAmount: ColumnType<string, string, string>;

  expectedRepayment: ColumnType<string | null, string | null, string | null>;

  expectedReturn: ColumnType<string | null, string | null, string | null>;
}

export type InvoiceFundingDetailDb = Selectable<InvoiceFundingDetailTable>;

export type InvoiceFundingDetailCreateDb = Insertable<InvoiceFundingDetailTable>;

export type InvoiceFundingDetailUpdateDb = Updateable<InvoiceFundingDetailTable>;
