// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table invoice.invoice_document */
export default interface InvoiceDocumentTable {
  id: ColumnType<string, string | undefined, string>;

  invoiceId: ColumnType<string, string, string>;

  documentType: ColumnType<string, string, string>;

  fileUrl: ColumnType<string, string, string>;

  fileName: ColumnType<string | null, string | null, string | null>;

  fileSizeBytes: ColumnType<string | null, string | null, string | null>;

  mimeType: ColumnType<string | null, string | null, string | null>;

  ipfsHash: ColumnType<string | null, string | null, string | null>;

  uploadedBy: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type InvoiceDocumentDb = Selectable<InvoiceDocumentTable>;

export type InvoiceDocumentCreateDb = Insertable<InvoiceDocumentTable>;

export type InvoiceDocumentUpdateDb = Updateable<InvoiceDocumentTable>;
