// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table invoice.invoice_default */
export default interface InvoiceDefaultTable {
  id: ColumnType<string, string | undefined, string>;

  invoiceId: ColumnType<string, string, string>;

  defaultedAt: ColumnType<string, string, string>;

  gracePeriodEnd: ColumnType<string, string, string>;

  collectionInitiatedAt: ColumnType<string | null, string | null, string | null>;

  collectionAgency: ColumnType<string | null, string | null, string | null>;

  recoveredAmountCents: ColumnType<string | null, string | null, string | null>;

  recoveryCostCents: ColumnType<string | null, string | null, string | null>;

  finalLossCents: ColumnType<string | null, string | null, string | null>;

  collectionStatus: ColumnType<string | null, string | null, string | null>;

  notes: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type InvoiceDefaultDb = Selectable<InvoiceDefaultTable>;

export type InvoiceDefaultCreateDb = Insertable<InvoiceDefaultTable>;

export type InvoiceDefaultUpdateDb = Updateable<InvoiceDefaultTable>;
