// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as PayerCompanyTable } from './PayerCompany';
import type { default as PayerRelationshipTable } from './PayerRelationship';

export default interface BusinessSchema {
  'business.payerCompany': PayerCompanyTable;

  'business.payerRelationship': PayerRelationshipTable;
}
