// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table business.payer_relationship */
export default interface PayerRelationshipTable {
  id: ColumnType<string, string | undefined, string>;

  organizationId: ColumnType<string, string, string>;

  payerCompanyId: ColumnType<string, string, string>;

  totalInvoicesCount: ColumnType<number | null, number | null, number | null>;

  paidOnTimeCount: ColumnType<number | null, number | null, number | null>;

  latePaymentCount: ColumnType<number | null, number | null, number | null>;

  defaultCount: ColumnType<number | null, number | null, number | null>;

  averagePaymentDelayDays: ColumnType<string | null, string | null, string | null>;

  reliabilityScore: ColumnType<string | null, string | null, string | null>;

  firstInvoiceDate: ColumnType<string | null, string | null, string | null>;

  lastInvoiceDate: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  totalInvoicesValue: ColumnType<string | null, string | null, string | null>;
}

export type PayerRelationshipDb = Selectable<PayerRelationshipTable>;

export type PayerRelationshipCreateDb = Insertable<PayerRelationshipTable>;

export type PayerRelationshipUpdateDb = Updateable<PayerRelationshipTable>;
