// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table business.payer_company */
export default interface PayerCompanyTable {
  id: ColumnType<string, string | undefined, string>;

  name: ColumnType<string, string, string>;

  legalName: ColumnType<string | null, string | null, string | null>;

  taxId: ColumnType<string | null, string | null, string | null>;

  industry: ColumnType<string | null, string | null, string | null>;

  website: ColumnType<string | null, string | null, string | null>;

  email: ColumnType<string | null, string | null, string | null>;

  phone: ColumnType<string | null, string | null, string | null>;

  addressLine1: ColumnType<string | null, string | null, string | null>;

  addressLine2: ColumnType<string | null, string | null, string | null>;

  city: ColumnType<string | null, string | null, string | null>;

  state: ColumnType<string | null, string | null, string | null>;

  postalCode: ColumnType<string | null, string | null, string | null>;

  country: ColumnType<string | null, string | null, string | null>;

  creditScore: ColumnType<string | null, string | null, string | null>;

  paymentTermsDays: ColumnType<number | null, number | null, number | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type PayerCompanyDb = Selectable<PayerCompanyTable>;

export type PayerCompanyCreateDb = Insertable<PayerCompanyTable>;

export type PayerCompanyUpdateDb = Updateable<PayerCompanyTable>;
